# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diad', '0004_auto_20150515_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albumes'},
        ),
        migrations.AlterModelOptions(
            name='fotos',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterField(
            model_name='album',
            name='url',
            field=models.ImageField(upload_to=b'diad/static/img/portada'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='url',
            field=models.ImageField(max_length=250, upload_to=b'diad/static/img/album/%Y'),
        ),
    ]
