"""
Django settings for uniforme project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import logging
import dj_database_url

# Variables para la App
APP_NAME = 'diad'

## Twitter ##
TW_KEY = os.environ.get('TWITTER_KEY')
TW_SECRET = os.environ.get('TWITTER_SECRET')
TW_TOKEN = os.environ.get('TWITTER_TOKEN')
TW_TOKEN_SECRET = os.environ.get('TWITTER_TOKEN_SECRET')

## Facebook ##
FB_API = os.environ.get('FACEBOOK_API')
FB_SECRET = os.environ.get('FACEBOOK_SECRET')
FB_TOKEN = os.environ.get('FACEBOOK_TOKEN')
FB_TOKEN_SECRET = os.environ.get('FACEBOOK_TOKEN_SECRET')


ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8m#q=b4cy(5%-wkplwgq*hr1gdamx9fi&r^u-o_bk)hs5d)k3u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'uniforme.scout.org.ve',
    'localhost'
]

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    APP_NAME,
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
)

ROOT_URLCONF = 'uniforme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'diad.context_processors.copyright',
            ],
        },
    },
]

WSGI_APPLICATION = 'uniforme.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        'NAME': 'scouts_diauniforme',
        'USER': 'root'
    }
}

# db_from_env = dj_database_url.config()
# DATABASES['default'].update(db_from_env)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-LA'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
''' STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'portada'),
    os.path.join(BASE_DIR, 'update'),
)'''
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
